add_lunch_combo saosp_angler-userdebug
add_lunch_combo saosp_bullhead-user
add_lunch_combo saosp_mako-userdebug
add_lunch_combo saosp_shamu-user
add_lunch_combo saosp_flo-userdebug
add_lunch_combo saosp_flounder-userdebug
add_lunch_combo saosp_hammerhead-userdebug
